
include:
  - board: nice_nano_v2
    shield: khonsu
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano
    shield: corne_left
  - board: nice_nano
    shield: corne_right
