
include:
  - board: nice_nano_v2
    shield: khonsu
  - board: nice_nano_v2
    shield: khorne_left
  - board: nice_nano_v2
    shield: khorne_right
  - board: nice_nano_v2
    shield: settings_reset
